### ISSUE TITLE
Compliance of Google Analytics with the Labs Terms of use

### ISSUE THREAD

**Issue by ricordisamoa** [cdrini/wikidata-timeline#1]
https://wikitech.wikimedia.org/wiki/Wikitech:Labs_Terms_of_use#What_can_and_can.E2.80.99t_be_done_with_user_information.3F
@slaporte

**Comment by slaporte** [comment]
Hi @ricordisamoa and @cdrini, you may use Google Analytics on your project on Wikimedia Tool Labs as long as you include your own proper privacy statement. Here is the statement I recommend for the requirements in the [Labs TOS](https://wikitech.wikimedia.org/wiki/Wikitech:Labs_Terms_of_use#What_can_and_can.E2.80.99t_be_done_with_user_information.3F) with Google Analytics, and you should also explain any other user data the site collects.

_This site was made by [your name/username and contact]. It uses [Google Analytics](https://www.google.com/intl/en/analytics/learn/privacy.html) to find out how many people visit it and some related information. You can opt out of Google Analytics by [installing a browser add-on](https://tools.google.com/dlpage/gaoptout)._

**Comment by ricordisamoa** [comment]
Thanks @slaporte!

**Comment by cdrini** [comment]
Thanks for the heads up @ricordisamoa, and thanks for the suggestion @slaporte! I'll put in a fix tomorrow and add the disclaimer.

**Comment by ricordisamoa** [comment]
Great tool BTW.

**Comment by cdrini** [comment]
Ok, the disclaimer should now appear on the [main page](https://tools.wmflabs.org/wikidata-timeline/) (although a hard refresh might be necessary).
