### ISSUE TITLE
Paintings with P571 renders not well 

### ISSUE THREAD

**Issue by fnielsen** [cdrini/wikidata-timeline#3]
Paintings with P571 renders not well. See  the query:

https://tools.wmflabs.org/wikidata-timeline/#/timeline?title=maleri&query=CLAIM[170:979541]&languages=en,fr

cf. https://da.wikipedia.org/wiki/V%C3%A6rker_af_Martinus_R%C3%B8rbye

**Comment by fnielsen** [comment]
Perhaps a URL parameter could determine what a missing endtime should mean: either endtime=starttime or endtime=present.

**Comment by cdrini** [comment]
Good catch! I always thought P571 was a little ambiguous.

I added a param called `defeaultEndTime` which can be either `now` or `start` . Here's the timeline now: https://tools.wmflabs.org/wikidata-timeline/#/timeline?title=maleri&query=CLAIM[170:979541]&languages=en,fr&defaultEndTime=start

**Comment by fnielsen** [comment]
It works for me now. Thanks!
